<?php

namespace Backend\Services;

use Backend\Config\Database;
use PDO;

/**
 * DoctorLoginRouter
 * 
 * Handles doctor login routing based on profile_status.
 * Determines where to redirect a doctor after successful authentication.
 * 
 * Routing Logic:
 *   draft       → Resume Onboarding (from last completed step)
 *   submitted   → Profile Under Review
 *   approved    → Payout Setup (if no payout exists) or Dashboard
 *   rejected    → Resubmit with admin notes
 *   active      → Doctor Dashboard
 *   suspended   → Account Suspended
 *   payout_pending → Payout Setup
 */
class DoctorLoginRouter
{
    private ProfileStatusService $statusService;
    private PDO $db;

    public function __construct()
    {
        $this->statusService = new ProfileStatusService();
        $this->db = Database::getInstance();
    }

    /**
     * Determine the post-login route for a doctor.
     * This is the main entry point called after successful authentication.
     * 
     * @param string $userId   The authenticated doctor's user ID
     * @return array{route: string, action: string, status: string, message: string}
     */
    public function getLoginRoute(string $userId): array
    {
        $status = $this->statusService->getCurrentStatus($userId);

        if ($status === null) {
            return $this->buildResponse(
                '/onboarding/basic-info',
                'start_onboarding',
                'draft',
                'No profile found. Starting onboarding...'
            );
        }

        return $this->statusService->getRoutingAction($userId);
    }

    /**
     * Handle doctor login — verifies credentials and returns routing info.
     * 
     * @param string $email    Doctor's email
     * @param string $password Plaintext password
     * @return array{success: bool, message: string, route: ?string, action: ?string, token: ?string}
     */
    public function handleDoctorLogin(string $email, string $password): array
    {
        // Step 1: Find user by email
        $stmt = $this->db->prepare('
            SELECT u.id, u.email, u.password, u.user_type, u.full_name, u.is_active,
                   dp.profile_status, dp.registration_step
            FROM users u
            LEFT JOIN doctor_profiles dp ON u.id = dp.user_id
            WHERE u.email = ? AND u.user_type = "doctor"
            LIMIT 1
        ');
        $stmt->execute([$email]);
        $user = $stmt->fetch(PDO::FETCH_ASSOC);

        if (!$user) {
            return [
                'success' => false,
                'message' => 'No account found with this email.',
                'route' => null,
                'action' => null,
                'token' => null,
            ];
        }

        // Step 2: Verify password
        if (!\Backend\Models\User::verifyPassword($password, $user['password'])) {
            return [
                'success' => false,
                'message' => 'Invalid password.',
                'route' => null,
                'action' => null,
                'token' => null,
            ];
        }

        // Step 3: Check if account is active
        if (!$user['is_active']) {
            return [
                'success' => false,
                'message' => 'Account has been deactivated. Please contact support.',
                'route' => null,
                'action' => null,
                'token' => null,
            ];
        }

        // Step 4: Get login route based on profile_status
        $routing = $this->getLoginRoute($user['id']);

        return [
            'success' => true,
            'message' => 'Login successful.',
            'route' => $routing['route'],
            'action' => $routing['action'],
            'status' => $routing['status'] ?? $user['profile_status'] ?? 'draft',
            'token' => null, // Token will be generated by auth middleware
            'user' => [
                'id' => $user['id'],
                'email' => $user['email'],
                'full_name' => $user['full_name'],
                'profile_status' => $user['profile_status'] ?? 'draft',
                'registration_step' => $user['registration_step'] ?? 'basic_info',
            ],
        ];
    }

    /**
     * Build a standard route response.
     */
    private function buildResponse(string $route, string $action, string $status, string $message): array
    {
        return [
            'route' => $route,
            'action' => $action,
            'status' => $status,
            'message' => $message,
        ];
    }
}