import 'package:frontend/core/errors/app_exceptions.dart';
import 'package:frontend/core/storage/shared_pref_service.dart';
import 'package:frontend/modules/auth/data/datasources/auth_api.dart';
import 'package:frontend/modules/auth/data/models/user_model.dart';

class AuthRepository {
  AuthRepository({AuthApi? authApi, SharedPrefService? prefs})
    : _api = authApi ?? AuthApi(),
      _prefs = prefs ?? SharedPrefService.instance;

  final AuthApi _api;
  final SharedPrefService _prefs;

  // ─── Validation ───────────────────────────────────────────────────────────

  String? _validateRegisterFields({
    required String name,
    required String email,
    required String password,
  }) {
    // Full name
    if (name.trim().isEmpty) {
      return 'Full name is required.';
    }
    if (name.trim().length < 2) {
      return 'Name must be at least 2 characters.';
    }
    if (!RegExp(r"^[a-zA-Z\s'\-\.]+$").hasMatch(name.trim())) {
      return 'Name can only contain letters, spaces, hyphens, or apostrophes.';
    }

    // Email
    if (email.trim().isEmpty) {
      return 'Email is required.';
    }
    if (!RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$').hasMatch(email.trim())) {
      return 'Enter a valid email address.';
    }

    // Password
    if (password.isEmpty) {
      return 'Password is required.';
    }
    if (password.length < 8) {
      return 'Password must be at least 8 characters.';
    }
    if (!RegExp(r'[A-Z]').hasMatch(password)) {
      return 'Password must contain at least one uppercase letter.';
    }
    if (!RegExp(r'[0-9]').hasMatch(password)) {
      return 'Password must contain at least one number.';
    }
    if (!RegExp(r'[!@#\$%^&*(),.?":{}|<>]').hasMatch(password)) {
      return 'Password must contain at least one special character.';
    }

    return null;
  }

  String? _validateLoginFields({
    required String email,
    required String password,
  }) {
    if (email.trim().isEmpty) {
      return 'Email is required.';
    }
    if (!RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$').hasMatch(email.trim())) {
      return 'Enter a valid email address.';
    }
    if (password.isEmpty) {
      return 'Password is required.';
    }

    return null;
  }

  // ─── Register ─────────────────────────────────────────────────────────────
  Future<UserModel> register({
    required String name,
    required String email,
    required String password,
    required String role,
  }) async {
    // 1. Validate locally — no network call if invalid
    final error = _validateRegisterFields(
      name: name,
      email: email,
      password: password,
    );
    if (error != null) throw ServerException(error, statusCode: 0);

    // 2. Call API — token auto-generated by backend
    final user = await _api.register(
      name: name.trim(),
      email: email.trim().toLowerCase(),
      password: password,
      role: role,
    );

    // 3. Persist session locally
    await _prefs.saveUser(
      role: user.role,
      token: user.token,
      name: user.name,
      email: user.email,
    );

    return user;
  }

  // ─── Login ────────────────────────────────────────────────────────────────
  Future<UserModel> login({
    required String email,
    required String password,
  }) async {
    // 1. Validate locally
    final error = _validateLoginFields(email: email, password: password);
    if (error != null) throw ServerException(error, statusCode: 0);

    // 2. Call API
    final user = await _api.login(
      email: email.trim().toLowerCase(),
      password: password,
    );

    // 3. Persist session locally
    await _prefs.saveUser(
      role: user.role,
      token: user.token,
      name: user.name,
      email: user.email,
    );

    return user;
  }

  // ─── Restore session ──────────────────────────────────────────────────────
  UserModel? tryRestoreSession() {
    final token = _prefs.getToken();
    final role = _prefs.getRole();
    final name = _prefs.getName();
    final email = _prefs.getEmail();

    // All fields must exist for a valid session
    if (token == null ||
        role == null ||
        name == null ||
        email == null) {
      return null;
    }

    return UserModel(
      role: role,
      token: token,
      name: name,
      email: email,
    );
  }

  bool get isLoggedIn => _prefs.isLoggedIn;

  // ─── Logout ───────────────────────────────────────────────────────────────
  Future<void> logout() async {
    await _prefs.clearUser();
    // await _api.logout(); // uncomment when backend endpoint is ready
  }
}
